### PR TITLE
Add Typescript declarations for nlog

### PR DESCRIPTION
**Pull request by Keyslam**
This pull request adds Typescript declarations for the nlog module. That way it can be used with transpilers like TSTL.

Perhaps it would be a good idea to expand it to declarations for all modules?

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
Are the necessary `require` is performed when `require` is called from TS? If I'd add more type definitions, I'd maybe create folder "definitions" and put all definitions file there.

**Comment by Keyslam** [comment]
Typescript will require you to import it, which will transpile to a require.

Both of these are valid:
```typescript
import { warn } from "nlog";

warn("Test", "Test Warning");
```

```typescript
import * as Nlog from "nlog";

Nlog.warn("Test", "Test Warning");
```

Unfortunately it's currently not supported to have definitions separate from the Lua source. This could and should be fixed in the future.

**Comment by MikuAuahDark** [comment]
My intention of placing it in separate folder is to make the root directory
(the actual libraries) clean from type definitions. Of course a notice must
be added that the definition file must be placed beside the Lua file itself.

Pada tanggal Min, 5 Jul 2020 23.51, Justin van der Leij <
notifications@github.com> menulis:

**Comment by Keyslam** [comment]
I think that's a nice solution to keep things organized. However at that point, would a separate repository with declarations work better? It would mirror the folder structure of this repository.
Then the user could clone both, merge them, and it should all work.

**Comment by MikuAuahDark** [comment]
I don't think a separate repository is necessary because user can just use
the "Raw" button and save the file, as any other scripts in here except
NWFC which I plan to move back to its original repo (and use submodule).

Pada tanggal Sen, 6 Jul 2020 00.01, Justin van der Leij <
notifications@github.com> menulis:

**Pull request merged**
